wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    code_path: code/scripts/Example-5.py
    framework: huggingface
    huggingface_version: 4.21.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.15
    start_time: 1672411905.382447
    t:
      1:
      - 1
      - 9
      - 11
      - 40
      - 41
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 40
      - 41
      - 49
      - 55
      3:
      - 7
      - 23
      4: 3.8.15
      5: 0.13.2
      6: 4.21.1
      8:
      - 2
      - 5
