# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev68+g0be4eb3.d20221222'
__version_tuple__ = version_tuple = (0, 1, 'dev68', 'g0be4eb3.d20221222')
