wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    code_path: code/scripts/Example-1.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.15
    start_time: 1670868098.532844
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.8.15
      5: 0.13.2
      8:
      - 2
      - 5
activation:
  desc: null
  value: elu
append_shot:
  desc: null
  value: n
causality_factor:
  desc: null
  value: 0.5
causality_weight:
  desc: null
  value: type_0
checker_size:
  desc: null
  value: 5.0
data_layers:
  desc: null
  value: 8
data_neurons:
  desc: null
  value: 16
data_type:
  desc: null
  value: nn
depth_shift:
  desc: null
  value: n
earth_scale:
  desc: null
  value: n
empty_middle:
  desc: null
  value: n
event_factor:
  desc: null
  value: 0.9
exclude_source:
  desc: null
  value: n
exclude_topo:
  desc: null
  value: n
exclude_well:
  desc: null
  value: n
exp_factor:
  desc: null
  value: 1.0
exp_function:
  desc: null
  value: n
explode_reflector:
  desc: null
  value: n
factorization_type:
  desc: null
  value: additive
field_synthetic:
  desc: null
  value: n
initial_velocity:
  desc: null
  value: 3.0
initialization:
  desc: null
  value: varianceScaling
irregular_grid:
  desc: null
  value: y
last_vmultiplier:
  desc: null
  value: 5
lateral_spacing:
  desc: null
  value: 0.03
learning_rate:
  desc: null
  value: 0.001
loss_function:
  desc: null
  value: mse
max_depth:
  desc: null
  value: 1.0
max_offset:
  desc: null
  value: 8.6
middle_shot:
  desc: null
  value: n
model_type:
  desc: null
  value: marmousi
nu_units:
  desc: null
  value: unitless
num_epochs:
  desc: null
  value: 3000
num_layers:
  desc: null
  value: 12
num_neurons:
  desc: null
  value: 24
num_points:
  desc: null
  value: 1.0
plotting_factor:
  desc: null
  value: 1
project_name:
  desc: null
  value: GFATT_PINNs-11-pytorch-surface-inversion
rec_spacing:
  desc: null
  value: 10
reduce_after:
  desc: null
  value: 50
regular_station:
  desc: null
  value: n
rescale_plot:
  desc: null
  value: y
residual_network:
  desc: null
  value: n
save_folder:
  desc: null
  value: ./
scale_factor:
  desc: null
  value: 2
seed:
  desc: null
  value: 1234
sou_spacing:
  desc: null
  value: 10
station_factor:
  desc: null
  value: 0.1
tau_act:
  desc: null
  value: tanh
tau_multiplier:
  desc: null
  value: 1.0
until_cmb:
  desc: null
  value: y
use_wandb:
  desc: null
  value: y
v_multiplier:
  desc: null
  value: 3.0
velocity_loss:
  desc: null
  value: n
vertical_spacing:
  desc: null
  value: 0.01
well_depth:
  desc: null
  value: null
xid_well:
  desc: null
  value: 5
zid_receiver:
  desc: null
  value: 0
zid_source:
  desc: null
  value: 5
