wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.2
    start_time: 1670674721.046703
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.8.2
      5: 0.13.2
      8:
      - 1
      - 2
      - 5
