wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.15
    start_time: 1671222949.473707
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.8.15
      5: 0.13.2
      8:
      - 1
      - 2
      - 5
